
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: workshop-gitops
images:
- name: workshop-gitops
  newName: regiocast/workshop-gitops
  newTag: 15a4682dace8698478c84256b95b9dd20ac3fa0e
