name: GitopsWorkshop
on:
    push:
        branches: [ master ]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Setup Go 1.15
              uses: actions/setup-go@v2
              with:
                go-version: ^1.15
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test
              run: |
                CGO_ENABLED=0 go test ./...
            - name: publish to registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                name: ${{ secrets.DOCKER_USERNAME }}/workshop-gitops
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                registry: ${{ secrets.DOCKER_REGISTRY }}
                tags: ${{ github.sha }}, latest
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Setup Kustomize
              uses: imranismail/setup-kustomize@v1
              with:
                kustomize-version: "3.6.1"
            - name: Update Kubernetes resources
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                cd kustomize/base
                kustomize edit set image workshop-gitops=${{ secrets.DOCKER_REGISTRY }}/$DOCKER_USERNAME/workshop-gitops:$GITHUB_SHA
                cat kustomization.yaml
            - name: Commit files
              run: |
                git config --local user.email "julian.koehn@regiocast.de"
                git config --local user.name "Julian Koehn"
                git commit -am "Bump docker tag"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
